trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'windows-latest'

variables:
  Configuration: 'Release'

steps:
  # Passaggio 1: Usa .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Passaggio 2: Compila tutti i progetti
  - script: |
      dotnet build DashBe/DashBe.sln -c $(Configuration)
    displayName: 'Build Solution'

  # Passaggio 3: Genera i pacchetti NuGet per ciascun progetto
  - script: |
      dotnet pack DashBe/DashBe.Domain/DashBe.Domain.csproj -c $(Configuration) --output $(Build.ArtifactStagingDirectory)
      dotnet pack DashBe/DashBe.Application/DashBe.Application.csproj -c $(Configuration) --output $(Build.ArtifactStagingDirectory)
      dotnet pack DashBe/DashBe.Infrastructure/DashBe.Infrastructure.csproj -c $(Configuration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack NuGet Packages'

  # Passaggio 4: Debug - Verifica i pacchetti generati nella directory di staging
  - script: dir "$(Build.ArtifactStagingDirectory)"
    displayName: 'Debug Artifact Staging Directory'

  # Passaggio 5: Pubblica tutti i pacchetti NuGet su Azure Artifacts
  - script: |
      nuget.exe push "$(Build.ArtifactStagingDirectory)/*.nupkg" -Source "https://pkgs.dev.azure.com/x-code-group/CryptoSignature/_packaging/DashBeArtifacts/nuget/v3/index.json" -ApiKey "AzureArtifacts" -SkipDuplicate
    displayName: 'Push NuGet Packages to Azure Artifacts'
    env:
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/x-code-group/CryptoSignature/_packaging/DashBeArtifacts/nuget/v3/index.json", "username":"AzureDevOps", "password":"$(System.AccessToken)"}]}'
