trigger:
  branches:
    include:
      - main
      - Develop
      - DashBe.Domain

pool:
  vmImage: 'windows-latest'

steps:
  # Installa il .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Compila il progetto DashBe.Domain
  - script: dotnet build $(System.DefaultWorkingDirectory)\DashBe\DashBe.Domain\DashBe.Domain.csproj --configuration Release
    displayName: 'Build DashBe.Domain'

  # Esegui il packing per DashBe.Domain
  - script: dotnet pack $(System.DefaultWorkingDirectory)\DashBe\DashBe.Domain\DashBe.Domain.csproj --configuration Release
    displayName: 'Pack DashBe.Domain'

  # Copia il file .nupkg nella directory di staging
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)\DashBe\DashBe.Domain\bin\Release'
      Contents: '**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Debug: Elenca i file nella directory di staging
  - script: dir "$(Build.ArtifactStagingDirectory)"
    displayName: 'Debug Artifact Staging Directory'

  # Push NuGet Package al feed utilizzando il System.AccessToken
  - script: |
      nuget.exe push "$(Build.ArtifactStagingDirectory)\DashBe.Domain.1.0.0.nupkg" -Source "https://pkgs.dev.azure.com/x-code-group/CryptoSignature/_packaging/DashBeArtifacts/nuget/v3/index.json" -ApiKey "AzureArtifacts" -SkipDuplicate
    displayName: 'Push NuGet Package to DashBeArtifacts'
    env:
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/x-code-group/CryptoSignature/_packaging/DashBeArtifacts/nuget/v3/index.json","username":"AzureDevOps","password":"$(System.AccessToken)"}]}'
