trigger:
  branches:
    include:
      - main
      - Develop
      - DashBe.Domain

pool:
  vmImage: 'windows-latest'

steps:
  # Debug: Elenca tutte le variabili di ambiente
  - script: set
    displayName: 'List All Environment Variables'

  # Debug: Verifica se la variabile NuGet_PAT è visibile e il suo valore
  - script: |
      echo "Testing NuGet_PAT visibility"
      echo NuGet_PAT: $env:NUGET_PAT
    displayName: 'Check NuGet_PAT Environment Variable'

  # Debug: Verifica se il System.AccessToken è visibile e il suo valore
  - script: |
      echo "Testing System.AccessToken visibility"
      echo System.AccessToken: $env:SYSTEM_ACCESSTOKEN
    displayName: 'Check System.AccessToken Environment Variable'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  # Installa il .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Compila il progetto DashBe.Domain
  - script: dotnet build $(System.DefaultWorkingDirectory)\DashBe\DashBe.Domain\DashBe.Domain.csproj --configuration Release
    displayName: 'Build DashBe.Domain'

  # Esegui il packing per DashBe.Domain
  - script: dotnet pack $(System.DefaultWorkingDirectory)\DashBe\DashBe.Domain\DashBe.Domain.csproj --configuration Release
    displayName: 'Pack DashBe.Domain'

  # Copia il file .nupkg nella directory di staging
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)\DashBe\DashBe.Domain\bin\Release'
      Contents: '**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Debug: Elenca i file nella directory di staging
  - script: dir "$(Build.ArtifactStagingDirectory)"
    displayName: 'Debug Artifact Staging Directory'

  # Push NuGet Package al feed utilizzando NuGet_PAT
  - script: |
      nuget.exe push "$(Build.ArtifactStagingDirectory)\DashBe.Domain.1.0.0.nupkg" -Source "https://pkgs.dev.azure.com/x-code-group/CryptoSignature/_packaging/DashBeArtifacts/nuget/v3/index.json" -ApiKey $env:NUGET_PAT -SkipDuplicate
    displayName: 'Push NuGet Package to DashBeArtifacts'
