trigger:
  branches:
    include:
      - main
      - develop
      - DashBe.Domain

pool:
  vmImage: 'windows-latest'

steps:
  # Installa .NET SDK versione 8.0
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Restora i pacchetti NuGet per la Solution
  - script: dotnet restore DashBe.sln
    displayName: 'Restore NuGet Packages'

  # Compila la Solution
  - script: dotnet build DashBe.sln --configuration Release --no-restore
    displayName: 'Build Solution'

  # Pubblica gli artefatti
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'
